# build:
#   stage: build
#   script:
#     - docker build -t test_container .
#     - docker run -v .:/app test_container
# before_script:
#   - docker info
variables:
    CI_NAME: "gitlab"
    CI_EMAIL: "gitlab-ci@danielha.tk"
stages:
  - test
  - release
test-component-hass-image:
  stage: test
  except:
    variables:
      - $GITLAB_USER_LOGIN == $CI_NAME

  script:
    - docker build -t component_test -f Dockerfile.component .
    - docker run --rm component_test pytest #/usr/src/app/tests/components/test_lightingsm.py
    # -v $(pwd)/custom_components/lightingsm.py:/usr/src/app/homeassistant/components/lightingsm.py:ro 
    # -v $(pwd)/tests/test_lightingsm.py:/usr/src/app/tests/components/test_lightingsm.py:ro 
# test-component:
#   script:
#     - docker build -t ci_test -f Dockerfile.ci-test .
#     - docker run --rm  ci_test # -v $(pwd):/app:ro

release:
  stage: release
  when: on_success

  except:
    variables:
      - $GITLAB_USER_LOGIN == $CI_NAME
      
  tags: 
    - npm
  only:
    - master
  image: tarampampam/node:alpine
  script:
    - npm install
    - git config --global user.email $CI_EMAIL
    - git config --global user.name $CI_NAME
    - git config receive.advertisePushOptions true
    - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
    - npm run release
    - git push http://${CI_USER}:${CI_ACCESS_TOKEN}@gitlab.danielha.tk:80/HA/appdaemon-motion-lights.git --follow-tags $CI_COMMIT_REF_NAME:$CI_COMMIT_REF_NAME
# test:
#   script:
#     - docker build -t ci_test -f Dockerfile.ci-test .
#     - docker run --rm ci_test